name: EAS Preview Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        working-directory: ./client
        run: npm install

      - name: 🚀 Build APK
        working-directory: ./client
        run: eas build --platform android --profile preview --non-interactive
